### ISSUE TITLE
Code throwing error for llama3

### ISSUE THREAD

**Issue by rishibunti** [ollama4j/ollama4j-web-ui#2]
Project is not compatible for llama3 
After updating pom.xml for latest library of ollama4j to 1.0.70. It throwing error as following
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2024-05-13T13:16:38.7024776+05:30": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2024-05-13T13:16:38.7024776+05:30' could not be parsed, unparsed text found at index 27
 at [Source: (String)"{"models":[{"name":"llama3:8b","model":"llama3:8b","modified_at":"2024-05-13T13:16:38.7024776+05:30","size":4661224578,"digest":"a6990ed6be412c6a217614b0ec8e9cd6800a743d5dd7e1d7fbe9df09e61d5615","details":{"parent_model":"","format":"gguf","family":"llama","families":["llama"],"parameter_size":"8B","quantization_level":"Q4_0"},"expires_at":"0001-01-01T00:00:00Z"},{"name":"llama3:latest","model":"llama3:latest","modified_at":"2024-05-13T13:05:58.9216973+05:30","size":4661224578,"digest":"a6990ed6"[truncated 597 chars]; line: 1, column: 66] (through reference chain: io.github.amithkoujalgi.ollama4j.core.models.ListModelsResponse["models"]->java.util.ArrayList[0]->io.github.amithkoujalgi.ollama4j.core.models.Model["modified_at"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
	at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer._fromString(LocalDateTimeDeserializer.java:179)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:81)
	at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at io.github.amithkoujalgi.ollama4j.core.OllamaAPI.listModels(OllamaAPI.java:137)
	at io.github.amithkoujalgi.service.ChatService.getModelItems(ChatService.java:40)
	at io.github.amithkoujalgi.views.chat.ChatView.<init>(ChatView.java:57)

**Comment by amithkoujalgi** [comment]
@rishibunti does the issue still persist with latest updates?
